import { writeFileSync } from 'node:fs'
import { apiSpecCategories, commonStructNames } from '@saltify/milky-types/namings'

const typeExport = new Set(commonStructNames)

const allSpecs = apiSpecCategories.flatMap(category => category.apiSpecs)

const rawEndpointsDeclarations = []
for (const spec of allSpecs) {
  if (spec.inputStructName) {
    typeExport.add(spec.inputStructName)
  }
  if (spec.outputStructName) {
    typeExport.add(spec.outputStructName)
  }
  rawEndpointsDeclarations.push(`  ${spec.endpoint}: (${spec.inputStructName ? `param: ${spec.inputStructName}` : 'params?: undefined | null'}) => ${spec.outputStructName ?? 'void'};`)
}

const typeNames = [...typeExport]
const chunks = []
chunks.push(`/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// This file is generated by scripts/generate-api.ts`)

chunks.push(`import type { ${typeNames.join(', ')} } from '@saltify/milky-types'`)

chunks.push(`export type MilkyRawEndpoints = {`)
chunks.push(...rawEndpointsDeclarations)
chunks.push(`}`)

chunks.push(`export type { ${typeNames.join(', ')} }`)

writeFileSync('./src/api.gen.ts', chunks.join('\n'))
