import { readFileSync, writeFileSync } from 'node:fs'
import ts from 'typescript'

const sourcePath = './src/gen/zod.ts'
const outputPath = './src/gen/meta.ts'

const sourceFile = ts.createSourceFile(
  sourcePath,
  readFileSync(sourcePath, 'utf8'),
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TS,
)

function propertyNameToString(name: ts.PropertyName) {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) {
    return name.text
  }

  throw new TypeError(`Unsupported property name in ${sourcePath}`)
}

function findObjectProperty(object: ts.ObjectLiteralExpression, name: string) {
  for (const property of object.properties) {
    if (!ts.isPropertyAssignment(property)) {
      continue
    }

    if (propertyNameToString(property.name) === name) {
      if (!ts.isObjectLiteralExpression(property.initializer)) {
        throw new TypeError(`Expected ${name} to be an object in ${sourcePath}`)
      }

      return property.initializer
    }
  }

  throw new TypeError(`Missing ${name} in ${sourcePath}`)
}

function findZodApiCategories() {
  for (const statement of sourceFile.statements) {
    if (!ts.isVariableStatement(statement)) {
      continue
    }

    for (const declaration of statement.declarationList.declarations) {
      if (
        ts.isIdentifier(declaration.name)
        && declaration.name.text === 'zodApiCategories'
        && declaration.initializer
        && ts.isObjectLiteralExpression(declaration.initializer)
      ) {
        return declaration.initializer
      }
    }
  }

  throw new TypeError(`Missing zodApiCategories in ${sourcePath}`)
}

const categories = findZodApiCategories()
const lines = [
  '// Generated by scripts/generate-meta.mjs',
  'import type { zodApiCategories } from \'./zod\'',
  '',
  'type ApiCategories = typeof zodApiCategories',
  '',
  'export const endpointNamesByCategory = {',
]

for (const categoryProperty of categories.properties) {
  if (!ts.isPropertyAssignment(categoryProperty)) {
    continue
  }

  const categoryName = propertyNameToString(categoryProperty.name)
  if (!ts.isObjectLiteralExpression(categoryProperty.initializer)) {
    throw new TypeError(`Expected category ${categoryName} to be an object in ${sourcePath}`)
  }

  const apis = findObjectProperty(categoryProperty.initializer, 'apis')
  lines.push(`  ${categoryName}: [`)

  for (const endpointProperty of apis.properties) {
    if (!ts.isPropertyAssignment(endpointProperty)) {
      continue
    }

    lines.push(`    '${propertyNameToString(endpointProperty.name)}',`)
  }

  lines.push('  ],')
}

lines.push(
  '} as const satisfies {',
  '  readonly [C in keyof ApiCategories]: readonly (keyof ApiCategories[C][\'apis\'] & string)[]',
  '}',
  '',
)

writeFileSync(outputPath, lines.join('\n'))
