import { readFileSync, writeFileSync } from 'node:fs'
import ts from 'typescript'

const sourcePath = './src/gen/zod.ts'
const commonOutputPath = './src/gen/zod-common.ts'
const eventOutputPath = './src/gen/zod-event.ts'
const apiOutputPath = './src/gen/zod-api.ts'

const sourceText = readFileSync(sourcePath, 'utf8')
const sourceFile = ts.createSourceFile(
  sourcePath,
  sourceText,
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TS,
)

interface RuntimeDeclaration {
  readonly names: readonly string[]
  readonly statement: ts.Statement
  readonly dependencies: Set<string>
}

function getRuntimeDeclarationNames(statement: ts.Statement): string[] {
  if (ts.isFunctionDeclaration(statement) && statement.name) {
    return [statement.name.text]
  }

  if (!ts.isVariableStatement(statement)) {
    return []
  }

  return statement.declarationList.declarations.flatMap((declaration) => {
    if (!ts.isIdentifier(declaration.name)) {
      throw new TypeError(`Unsupported generated declaration in ${sourcePath}`)
    }

    return declaration.name.text
  })
}

const runtimeDeclarations: RuntimeDeclaration[] = []
const declarationByName = new Map<string, RuntimeDeclaration>()

for (const statement of sourceFile.statements) {
  const names = getRuntimeDeclarationNames(statement)
  if (names.length === 0) {
    continue
  }

  const declaration: RuntimeDeclaration = {
    names,
    statement,
    dependencies: new Set(),
  }

  runtimeDeclarations.push(declaration)
  for (const name of names) {
    if (declarationByName.has(name)) {
      throw new TypeError(`Duplicate generated declaration ${name} in ${sourcePath}`)
    }
    declarationByName.set(name, declaration)
  }
}

function collectDependencies(declaration: RuntimeDeclaration): void {
  function visit(node: ts.Node): void {
    if (ts.isIdentifier(node)) {
      const dependency = declarationByName.get(node.text)
      if (dependency && dependency !== declaration) {
        declaration.dependencies.add(node.text)
      }
    }

    ts.forEachChild(node, visit)
  }

  visit(declaration.statement)
}

for (const declaration of runtimeDeclarations) {
  collectDependencies(declaration)
}

function resolveClosure(rootName: string): Set<RuntimeDeclaration> {
  const root = declarationByName.get(rootName)
  if (!root) {
    throw new TypeError(`Missing generated declaration ${rootName} in ${sourcePath}`)
  }

  const closure = new Set<RuntimeDeclaration>()
  const pending = [root]

  while (pending.length > 0) {
    const declaration = pending.pop()!
    if (closure.has(declaration)) {
      continue
    }

    closure.add(declaration)
    for (const dependencyName of declaration.dependencies) {
      pending.push(declarationByName.get(dependencyName)!)
    }
  }

  return closure
}

const eventClosure = resolveClosure('Event')
const apiClosure = resolveClosure('zodApiCategories')
const commonDeclarations = new Set(
  [...eventClosure].filter(declaration => apiClosure.has(declaration)),
)
const eventDeclarations = new Set(
  [...eventClosure].filter(declaration => !commonDeclarations.has(declaration)),
)
const apiDeclarations = new Set(
  [...apiClosure].filter(declaration => !commonDeclarations.has(declaration)),
)

function collectExternalDependencies(
  declarations: ReadonlySet<RuntimeDeclaration>,
  externalDeclarations: ReadonlySet<RuntimeDeclaration>,
): string[] {
  const dependencies = new Set<string>()

  for (const declaration of declarations) {
    for (const dependencyName of declaration.dependencies) {
      const dependency = declarationByName.get(dependencyName)!
      if (externalDeclarations.has(dependency)) {
        dependencies.add(dependencyName)
      }
    }
  }

  return [...dependencies].sort()
}

function renderModule(
  declarations: ReadonlySet<RuntimeDeclaration>,
  commonImports: readonly string[] = [],
): string {
  const lines = [
    '// Generated by scripts/split-zod.ts. Do not edit.',
    'import { z } from \'zod\'',
  ]

  if (commonImports.length > 0) {
    lines.push(`import { ${commonImports.join(', ')} } from './zod-common'`)
  }

  lines.push('')

  for (const declaration of runtimeDeclarations) {
    if (!declarations.has(declaration)) {
      continue
    }

    lines.push(sourceText.slice(declaration.statement.getFullStart(), declaration.statement.end).trim(), '')
  }

  return lines.join('\n')
}

writeFileSync(commonOutputPath, renderModule(commonDeclarations))
writeFileSync(
  eventOutputPath,
  renderModule(
    eventDeclarations,
    collectExternalDependencies(eventDeclarations, commonDeclarations),
  ),
)
writeFileSync(
  apiOutputPath,
  renderModule(
    apiDeclarations,
    collectExternalDependencies(apiDeclarations, commonDeclarations),
  ),
)
